code --install-extension EditorConfig.EditorConfig
code --install-extension vscodevim.vim
code --install-extension ms-python.python
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension mjmcloug.vscode-elixir
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension eamodio.gitlens
code --install-extension teabyii.ayu
